version: '3.8'

services:
  web:
    image: php:8.1-fpm-alpine
    container_name: gridfieldrelationhandler_web
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-SS_gridfieldrelationhandler}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: gridfieldrelationhandler_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-SS_gridfieldrelationhandler}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: gridfieldrelationhandler_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
